/* Rapid API */
export const RAPID_API_KEY = process.env.REACT_APP_RAPID_API_KEY
export const RAPID_API_HOST = process.env.REACT_APP_RAPID_API_HOST

/* Firebase */
export const FIREBASE_API_KEY = process.env.REACT_APP_FIREBASE_API_KEY
export const FIREBASE_AUTH_DOMAIN = process.env.REACT_APP_FIREBASE_AUTH_DOMAIN
export const FIREBASE_PROJECT_ID = process.env.REACT_APP_REACT_APP_FIREBASE_PROJECT_ID
export const FIREBASE_STORAGE_BUCKET = process.env.REACT_APP_FIREBASE_STORAGE_BUCKET
export const FIREBASE_MESSAGING_SENDING_ID = process.env.REACT_APP_FIREBASE_MESSAGING_SENDING_ID
export const FIREBASE_API_ID = process.env.REACT_APP_FIREBASE_API_ID
export const FIREBASE_API_MEASUREMENT_ID = process.env.REACT_APP_FIREBASE_MEASUREMENT_ID